// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufyuaeekxyqcpigwihcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmeXVhZWVreHlxY3BpZ3dpaGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDY3OTksImV4cCI6MjA3MDcyMjc5OX0.Y3KAFu85AMCQ3DxWO7YNmoORazgOW1DM4g-g4eRo1Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});